'use client';

import React, { useEffect, useState } from 'react';
import Link from 'next/link';
import axios from 'axios';
import { BarChart3, Search, Activity, CheckCircle2, AlertTriangle, XCircle, ArrowRight, RefreshCw } from 'lucide-react';
import { getApiBase } from '@/lib/config';

export default function DecisionsPage() {
  const API_BASE = getApiBase();
  const [decisions, setDecisions] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [filterStatus, setFilterStatus] = useState<string>('ALL');
  const [searchQuery, setSearchQuery] = useState<string>('');

  useEffect(() => {
    fetchDecisions();
  }, [filterStatus]);

  const fetchDecisions = async () => {
    setLoading(true);
    try {
      const url = filterStatus === 'ALL' ? `${API_BASE}/api/decisions` : `${API_BASE}/api/decisions?status=${filterStatus}`;
      const res = await axios.get(url);
      setDecisions(res.data);
    } catch (err) {
      console.error('Fetch decisions error', err);
    } finally {
      setLoading(false);
    }
  };

  const filteredDecisions = decisions.filter(
    (d) =>
      d.original_query.toLowerCase().includes(searchQuery.toLowerCase()) ||
      d.location_name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      d.decision_code.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-6">
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 border-b border-slate-800 pb-6">
        <div>
          <h1 className="text-2xl sm:text-3xl font-extrabold text-slate-100 flex items-center gap-3">
            <BarChart3 className="w-7 h-7 text-cyan-400" />
            Decision Intelligence Registry
          </h1>
          <p className="text-sm text-slate-400 font-mono mt-1">
            Historical and active Living Decisions generated by ORCA Multi-Agent Pipeline.
          </p>
        </div>

        {/* Filter Buttons */}
        <div className="flex items-center gap-2 bg-slate-900/80 p-1.5 rounded-xl border border-slate-800">
          {['ALL', 'DECIDED', 'MONITORING', 'CHANGED'].map((st) => (
            <button
              key={st}
              onClick={() => setFilterStatus(st)}
              className={`px-3 py-1.5 rounded-lg text-xs font-mono font-bold transition-all ${
                filterStatus === st
                  ? 'bg-cyan-500/20 text-cyan-300 border border-cyan-500/40'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              {st}
            </button>
          ))}
        </div>
      </div>

      {/* SEARCH BAR */}
      <div className="relative">
        <Search className="w-4 h-4 text-slate-500 absolute left-4 top-3.5" />
        <input
          type="text"
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          placeholder="Filter decisions by query, location (e.g. Chennai), or code (ORCA-1042)..."
          className="w-full bg-slate-950/80 border border-slate-800 focus:border-cyan-500/40 rounded-2xl py-3 pl-11 pr-4 text-slate-100 text-xs font-mono focus:outline-none"
        />
      </div>

      {/* Decisions List Table */}
      {loading ? (
        <div className="glass-panel p-12 rounded-3xl text-center text-slate-400 font-mono">
          <RefreshCw className="w-8 h-8 animate-spin mx-auto text-cyan-400 mb-3" />
          Loading Decision Registry records...
        </div>
      ) : filteredDecisions.length === 0 ? (
        <div className="glass-panel p-12 rounded-3xl text-center text-slate-400 font-mono">
          No matching decisions found. Run a prompt from the Command Center!
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredDecisions.map((d) => {
            const badgeClass =
              d.recommendation === 'GO'
                ? 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40'
                : d.recommendation === 'CAUTION'
                ? 'bg-amber-500/20 text-amber-300 border-amber-500/40'
                : 'bg-rose-500/20 text-rose-300 border-rose-500/40';

            return (
              <div key={d.id} className="glass-panel p-5 rounded-3xl border-slate-800 glass-card-hover space-y-4 flex flex-col justify-between">
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <span className="font-mono text-xs text-cyan-400 font-bold px-2.5 py-0.5 rounded bg-cyan-500/10 border border-cyan-500/20">
                      {d.decision_code}
                    </span>
                    <span className={`px-3 py-0.5 rounded-xl text-xs font-mono font-bold border ${badgeClass}`}>
                      {d.recommendation}
                    </span>
                  </div>

                  <h3 className="font-semibold text-sm text-slate-100 line-clamp-2">
                    "{d.original_query}"
                  </h3>

                  <div className="grid grid-cols-2 gap-2 text-xs font-mono text-slate-400 pt-2 border-t border-slate-800/80">
                    <div>
                      <span className="text-[10px] uppercase text-slate-500 block">Sector</span>
                      <span className="text-slate-200 font-bold">{d.location_name}</span>
                    </div>
                    <div>
                      <span className="text-[10px] uppercase text-slate-500 block">Overall Score</span>
                      <span className="text-cyan-400 font-bold">{d.overall_score}/100</span>
                    </div>
                  </div>
                </div>

                <div className="pt-3 border-t border-slate-800 flex items-center justify-between text-xs font-mono">
                  <span className="text-slate-500 text-[10px]">{new Date(d.created_at).toLocaleDateString()}</span>
                  <Link
                    href={`/decisions/${d.id}`}
                    className="flex items-center gap-1 text-cyan-400 hover:text-cyan-300 font-bold"
                  >
                    <span>Inspect</span>
                    <ArrowRight className="w-3.5 h-3.5" />
                  </Link>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
